drop schema if exists lab6_maven cascade;
create schema lab6_maven;

CREATE TABLE lab6_maven.school_class
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    teacher_name VARCHAR(255)                            NOT NULL,
    grade_level  SMALLINT                                NOT NULL,
    school_year  SMALLINT                                NOT NULL,
    CONSTRAINT pk_schoolclass PRIMARY KEY (id)
);

CREATE TABLE lab6_maven.student
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255)                            NOT NULL,
    last_name       VARCHAR(255)                            NOT NULL,
    school_class_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

ALTER TABLE lab6_maven.student
    ADD CONSTRAINT FK_STUDENT_ON_SCHOOL_CLASS FOREIGN KEY (school_class_id) REFERENCES lab6_maven.school_class (id);


CREATE TABLE lab6_maven.student_grade
(
    id              BIGINT            NOT NULL,
    grade           INTEGER           NOT NULL,
    weight          INTEGER DEFAULT 0 NOT NULL,
    date            date              NOT NULL,
    school_class_id BIGINT            NOT NULL,
    student_id      BIGINT            NOT NULL,
    CONSTRAINT pk_studentgrade PRIMARY KEY (id)
);

ALTER TABLE lab6_maven.student_grade
    ADD CONSTRAINT FK_STUDENTGRADE_ON_SCHOOL_CLASS FOREIGN KEY (school_class_id) REFERENCES lab6_maven.school_class (id);

ALTER TABLE lab6_maven.student_grade
    ADD CONSTRAINT FK_STUDENTGRADE_ON_STUDENT FOREIGN KEY (student_id) REFERENCES lab6_maven.student (id);
