drop schema if exists lab6_maven cascade;
create schema lab6_maven;

CREATE TABLE lab6_maven.school_class
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    teacher_name VARCHAR(255),
    grade_level  INTEGER                                 NOT NULL,
    CONSTRAINT pk_schoolclass PRIMARY KEY (id)
);

